org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official


LEGAL_PROVIDER_NAME=Full legal name or registered company
LEGAL_PROVIDER_ADDRESS=Complete service address, country
LEGAL_PROVIDER_EMAIL=Monitored support and privacy email address
PRIVACY_POLICY_URL=https://example.com/privacy
MAP_TILE_URL=foo